baseURL = "http://www.stevenhancock.ca/"
languageCode = "en-us"
title = "Steven Hancock"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Steven Hancock"
    description = "Steven's personal site"
    githubUsername = "shancock-va"
    accent = "#278fe5"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/articles/"
    name = "Articles"
    weight = 3

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/shancock-va/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/hancock_steven"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/stevenmhancock/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://medium.com/@hancock.steven.m"
    name = "medium-m"
    weight = 4
